### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/scala#658]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/scala/issues/649)
- [x] [Add key features](https://github.com/exercism/scala/issues/650)
- [x] [Add tags](https://github.com/exercism/scala/issues/651)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/scala/issues/652)
- [x] [Update status of track](https://github.com/exercism/scala/issues/656)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/scala/issues/657)
- [ ] [Pass linting checks](https://github.com/exercism/scala/issues/653)
- [ ] [Build Test Runner](https://github.com/exercism/scala/issues/654)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/scala/issues/655) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/scala/issues/664)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
